### PR TITLE
Improve perf by reducing calls to mh.toB58String

### PR DESCRIPTION
**Pull request by dignifiedquire**
We were abusing this encoding very heavily. Ref https://github.com/libp2p/js-peer-id/pull/44

### CODE REVIEW

**Comment by dignifiedquire** [comment]
Latest orbit build including these changes: https://ipfs.io/ipfs/QmZBWsCwgQ6x7ZSBWXufAFirKJ64j39r6yygTm31sdCrMY

**Comment by diasdavid** [comment]
@dignifiedquire could you please PR this against the bitswap 1.1.0? This will cause a bunch of annoying merge conflicts and for the time being, it is not a priority, can easily be shipped by next week with the other PR

**Comment by dignifiedquire** [comment]
Given these changes are ready to be used and very helpful I don't think it makes sense to delay them untill the 1.1 PR is ready. I will have to redo most of this anyway for that branch, so lets ship this so it can be used amd I will rebase and fixup the 1.1 branch afterwards.

**Comment by dignifiedquire** [comment]
Closing in favor of #83

**Pull request closed without merging**
