### PR TITLE
chore: update multicodec

### PR DESCRIPTION
**Pull request by hacdias**
Updating multicodec to 1.0.0 as we decided to bump it to 1.0.0 and deprecate 0.x.

### CODE REVIEW

**Comment by adamsoffer** [comment]
@hacdias this commit seems to have caused a compilation error in typescript applications that depend on this library.

image

I believe this is because it's referring to a file that's been removed in the latest multicodec release (`name-table.js`)?

**Comment by adamsoffer** [comment]
ah looks like this was addressed here https://github.com/ipfs/js-ipfs-bitswap/pull/209

**Comment by hacdias** [comment]
@adamsoffer yes, and only Windows is failing, as on master. Merry Christmas too!

**Comment by achingbrain** [comment]
This was done as part of #206

**Pull request closed without merging**
