### PR TITLE
do NOT merge test thisconnect/protons#dep/remove/brfs

### PR DESCRIPTION
**Pull request by thisconnect**
https://github.com/dignifiedquire/protons/pull/3

### CODE REVIEW

**Comment by thisconnect** [comment]
both were hanging for 15min, interestingly when canceling Node v8, the Node v6 test stopped hang and failed immediately.
https://travis-ci.org/ipfs/js-ipfs-bitswap/builds/291232204

I close this one ok?

**Comment by dignifiedquire** [comment]
@diasdavid can you check please why travis is so unhappy?

**Comment by diasdavid** [comment]
@dignifiedquire something happened after our aegir tests and 12.1.0 that now an `npm test` never leaves the Node.js tests and in CI sometimes it works, others it hands forever. Could you try reproducing it locally and see if it happens for you as well?

**Comment by dryajov** [comment]
@diasdavid @dignifiedquire I can confirm, I see that too.

**Comment by diasdavid** [comment]
protons has been updated and it is on master of bitswap too. Thanks @thisconnect for pushing a fix everywhere \o/

**Pull request closed without merging**
