### PR TITLE
Move process to dev dependencies

### PR DESCRIPTION
**Pull request by bgins**
Hello :wave:. We recently noticed that some modern bundlers moving away from shimming node built-ins (https://github.com/vitejs/vite/issues/2723#issuecomment-808690781), and that `process` is included as a dependency here. 

This PR would move `process` from `dependencies` to `devDependencies`. It appears to only be used in tests and benchmarks, and everything builds and tests pass afterwards.

I think this change would be alright, but certainly feel free to decline or request changes if I have overlooked something! :pray:

### CODE REVIEW

**Comment by lidel** [comment]
@achingbrain sounds like you are the most familiar with this area of  js-ipfs?

**Comment by jorishermans** [comment]
What is the process of this issue?

**Comment by BigLep** [comment]
@Gozala : We're hoping during your tribute week you can review and merge.

**Review by achingbrain — APPROVED** [review]
Good catch, thanks!

**Pull request merged**
