### PR TITLE
feature: ability to override default bitswap max message size

### PR DESCRIPTION
**Pull request by ya7ya**
This PR is a part of the fix for the browser to browser file transfer issue in `IPFS` https://github.com/ipfs/js-ipfs/issues/1019 .

This edit allows an override of `MAX_MESSAGE_SIZE` so it can be used in the browser via WebRTC Transport. I been testing and so far 32KB seem to work in the browser without getting throttled.

License: MIT
Signed-off-by: Yahya <ya7yaz@gmail.com>

### CODE REVIEW

**Comment by ya7ya** [comment]
hey @diasdavid , Can you take a look at this PR? 
This minor modification allows bitswap to change `MAX_MESSAGE_SIZE` so it can be used in the browser via WebRTC Transport. I been testing and so far 32KB seem to work in the browser without getting throttled.

Let me know what you think.

**Comment by Stebalien** [comment]
@diasdavid shouldn't this be handled by the WebRTC transport?

**Comment by diasdavid** [comment]
@ya7ya is this PR something you still think you can finish?

**Comment by ya7ya** [comment]
@diasdavid Hey david, I completely forgot about this PR, I'm so sorry about this. I'll try to finalize this and add the required tests as soon as possible. 🙇

**Comment by Stebalien** [comment]
There are a *lot* of changes here so it's a bit hard to tell what this is actually doing now but, if this is doing what the title says, this is very much the *wrong* fix. Is it really not possible (and much simpler) to have the WebRTC transport write at most 32KiB at a time?

**Comment by ya7ya** [comment]
hey @Stebalien , I rebased this PR to master so that's why there are alotta changes.

> if this is doing what the title says, this is very much the wrong fix.

Yes. This does what the title says. And I'd be very interested in doing the _correct_ fix and rejecting this PR if it's possible to override this at webRTC transport level.

**Comment by Stebalien** [comment]
It should be fairly easy to fix in the webRTC transport. Unfortunately, my understanding of js streams is rather limited (I generally avoid working on javascript).

**Comment by ya7ya** [comment]
@Stebalien I'm gonna look into it. probably we can throttle the pull request `conn` in the Transport itself. I'm not 100% sure but I'll see what I can do. Thanks for the tip, I appreciate your input 👍 💯

**Comment by dryajov** [comment]
@ya7ya I believe, we can use something like this to chunk the stream at the transport level - https://pull-stream.github.io/#pull-block.

**Comment by alanshaw** [comment]
+1 this needs to be handled in the webrtc libp2p transport.

**Comment by daviddias** [comment]
@vasco-santos, @jacobheun this PR suggests that the transports should get some benchmarking treatment.

There are two low hanging fruits to make things fast:
- The change that @ya7ya suggests for the WebRTC transport
- Creating a simple-peer module that doesn't rely on Readable Streams

**Comment by achingbrain** [comment]
I don't think this PR is necessary any more, the upstream issue it's supposed to fix has been addressed by libp2p refactors.

Please feel free to reopen if it's still a problem.

**Pull request closed without merging**
